### ISSUE TITLE
Explanation needed about Line

### ISSUE THREAD

**Issue by Ziqing19** [PeculiarVentures/GammaCV#120]
I am working on detecting vertical and horizontal lines in an image. The gm.pcLines works well on finding those lines. But I got confused when I was trying to get the middle point of the line.

As far as already known, the x1,y1,x2,y2 coordinates can be obtained by line.x1, line.y1 etc. 

This did work on horizontal lines and I have got something like `[0, 522, 1910, 522, 955, 522, 0, 0]`. But for a vertical line, I have got a line like `[0, -972190, 1910, 849950, 1, 1020, 0, 89.93994140625].` 

The y coordinates were big numbers, while the image itself is of 1910 * 1030. But this line indeed can be drawn by gm.canvasDrawLine().

So could you please give some explanation on the gm.Line object? What I want is the middle point coordinate of a vertical line.

**Comment by WorldThirteen** [comment]
Hi @Ziqing19!

The gm.Line object is mainly stored as coordinates of 2 points, but also contains additional data which could be described as:
```
[
  0: x coordinate of point 1,
  1: y coordinate of point 1,
  2: x coordinate of point 2,
  3: y coordinate of point 2,
  4: u coordinate in parallel coordinates u-v space, // optionally exist
  5: v coordinate in parallel coordinates u-v space, // optionally exist
  6: line length cache for calls of line.length, // optionally exist
  7: line slope (angle) for calls of line.angle, // optionally exist
]
```

Now more about vertical line problem. Due to the nature of how parallel coordinates inside gm.pcLines converted into euclidian space (x, y aka left, top) the vertical lines is described by the intersections with left and right coordinate bounds. Thatswhy vertical coordinates is such huge out of image bounds.

To treat your need, you could find an intersection for this vertical line with top and bottom borders of your image using `gm.Line.Interection(line1, line2);`

I made an example of such "cutting" the line here:
https://codepen.io/WorldThirteen/pen/NWpVrMb.

<details>
<summary>Code from pen for records:</summary>

```js
const green = 'rgb(0,208,147)';
const white = 'rgb(244,245,249)';
const red = 'rgb(255,103,136)';
const purple = 'rgb(143,112,250)';

// prepare canvas
const canvas = document.getElementById('canvas');

canvas.width = 1910;
canvas.height = 1030;
gm.canvasFill(canvas, 'rgb(13,9,26)');

// define example lines
const lineHorizontal = new gm.Line([0, 522, 1910, 522, 955, 522, 0, 0]);
const lineVertical = new gm.Line([0, -972190, 1910, 849950, 1, 1020, 0, 89.93994140625]);

// visualise it
gm.canvasDrawLine(canvas, lineHorizontal, white, 3);
gm.canvasDrawLine(canvas, lineVertical, white, 3);

// Find intersection for vertical line with bottom border of an image
const topIntersection = gm.Line.Intersection(
	new gm.Line(0, 0, 1910, 0),
	lineVertical,
);
// draw this intersection to visualise
gm.canvasFillCircle(canvas, topIntersection, 15, purple);

// Find intersection for vertical line with bottom border of an image
const bottomIntersection = gm.Line.Intersection(
	new gm.Line(0, 1030, 1910, 1030),
	lineVertical,
);
// draw this intersection to visualise
gm.canvasFillCircle(canvas, bottomIntersection, 15, green);

// Create new "bounded" line from intersections
const cutLine = new gm.Line(topIntersection[0], topIntersection[1], bottomIntersection[0], bottomIntersection[1]);

// Draw middle point of this line
gm.canvasFillCircle(
	canvas,
	[(cutLine.x2 - cutLine.x1) / 2 + cutLine.x1, (cutLine.y2 - cutLine.y1) / 2 + cutLine.y1],
  15,
	red,
);


```

</details>

**Comment by Ziqing19** [comment]
Thank you for your quick response! And the example code is really helping!
