### ISSUE TITLE
Question: Speeding up imageTensorFromURL?

### ISSUE THREAD

**Issue by rmdvector** [PeculiarVentures/GammaCV#195]
I have a pipeline that's basically
1. Capture Image From video object
2. gm.imageTensorFromURL
3. Processing
From profiling, it looks like imageTensorFromURL takes up over half the time of the processing pipeline, a typical run is (milliseconds)
image read 505 pipeline 676 hough Features 845 contours 850
For images around 3072x2140 on a Google Pixel 7. Is there any way to speed this up, aside from reducing the resolution? We need fairly high resolution images for upload.

**Comment by WorldThirteen** [comment]
@rmdvector, there is no practical possibility to speed `imageTensorFromURL` up a lot. The trick here is not to do it on each frame.
You'd like to offload everything to the GPU pipeline, ensuring you not processing each frame with the CPU.

To achieve this, you can use MediaInput, we might lack documentation on this on the website, but the sample usage might look like this:
```
//Create media input element from a video stream
const input = new gm.MediaInput(htmlVideoElement);

//It then could be used instead of a tensor
const op = gm.grayscale(input);
...
```

So you can get real-time feedback in high resolution, a resized smaller image to read and process image for some calculations if needed, and obtain a full-scale image from the pipeline for final upload.

If you need to upload each frame, then gm.imageTensorFromURL is your weak spot, because loading from GPU to RAM is always slow by its nature.

By the way, I am curious, can you tell us more about your project?

**Comment by rmdvector** [comment]
Thanks! I'll give that a try!
We're a mobile + web application that automates Bills of  Of Lading for the trucking industry. Sometimes a BOL needs to be scanned on the road, and we want to outline the detected page in realtime to ensure the document is centered.
I'm contemplating writing a GL kernel to do that heavy lifting, since even if I remove the .5 second delay in image data transfer it's still another 300ms or so to detect the rectangle on the page.
